# Generated by Django 4.0.4 on 2022-05-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('accno', models.CharField(max_length=12)),
                ('tmoney', models.CharField(max_length=5)),
            ],
        ),
    ]
