# Generated by Django 4.0.4 on 2022-05-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bankdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='chalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oname', models.CharField(max_length=40)),
                ('amount', models.CharField(max_length=40)),
                ('oplate', models.CharField(max_length=40)),
                ('ostate', models.CharField(max_length=40)),
            ],
        ),
    ]
